<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHT9G6xD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHT9G6xD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHT9G6xD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHT9G6xD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHT9G6xD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HT9G6xD',
    'container.build_id' => '72a00427',
    'container.build_time' => 1575882516,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHT9G6xD');
